### ISSUE TITLE
Add Facebook like button on Homepage

### ISSUE THREAD

**Issue by tvalentius** [BaliJS/balijs-web#26]

**Comment by Asutosh989** [comment]
Hi @tvalentius , I would like to try it. Can you please elaborate the issue?

**Comment by tvalentius** [comment]
Thank you for your interest @Asutosh989 , but this already solved on https://github.com/BaliJS/balijs-web/pull/27 ,

You can see the other issues here that is still open : https://github.com/BaliJS/balijs-web/issues
